PROJECT=ExeProject
SUBPROJECTS=../LibProject
INCLUDES=-I../LibProject
CXXFLAGS_BASE=-c -Wall -DNDEBUG -DWITH_PROFILER -pthread $(INCLUDES) 
CXXFLAGS_RELEASE= -O3 -DRELEASE
CXXFLAGS_DEBUG  = -O0 -g -DDEBUG
LIBRARY_PATH=-L../LibProject
LDFLAGS_BASE=../LibProject/$(TARGETDIR)/libLibProject.a
LDFLAGS_DEBUG=
LDFLAGS_RELEASE=
IGNORE_FILES=
EXECUTABLE=$(PROJECT)
#LIBRARY=$(addsuffix .a,$(addprefix lib,$(PROJECT)))
#DYNAMIC=$(addsuffix .so,$(addprefix lib,$(PROJECT)))

include ../MakefileBase

